[project]
authors = ["Martin Dudek <martin.dudek@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "mojo dictionary benchmarks"
name = "mojo-dictionary-benchmarks"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
python = "*"
matplotlib = "*" 

[tasks]

[feature.nightly]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]

[feature.nightly.dependencies]
max = "*"

[feature.stable]

[feature.stable.dependencies]
max = ">=24.5,<24.6"

[environments]
default = ["stable"]
nightly = ["nightly"]


