[workspace]
authors = ["Martin Dudek <martin.dudek@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-dictionary-benchmarks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.6.0.dev2025082505,<26"
